[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 80

[[proxy]]
# This proxy specifies only the backend, which is the only required field. In this example,
# request URIs are not modified when proxied.
backend = "http://0.0.0.0:8000/api"
